name: PvpParadise
main: fencingparry4.bukkit.PvpParadise.PvpParadise
version: 1.0
author: Emerson Dove
description: Says Hi
commands:
  pvpparadise:
    description: All args reateChest randomTP chestHelp hello
    usage: /command [optionalParam]